version: "3"
services:
    pixeldesk:
        build: .
        hostname: pixelkdesk
        container_name: pixelkdesk
        restart: always
        expose:
          - "5010"
        ports:
          - "5010:5010"
        networks:
          - local
        environment:
          - TIMEZONE=-3

networks:
    local:
        driver: bridge
